# Generated by Django 5.1.1 on 2024-09-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourate_players',
            field=models.ManyToManyField(related_name='fans', to='players.player'),
        ),
    ]
