

services:
  db:
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  redis:
    image: redis:latest
    ports:
      - "6379:6379"


  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  celery-beat:
    build: .
    command: ["celery", "-A", "soccer_player", "worker", "--beat", "-l" , "INFO"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis


volumes:
  postgres_data: