# Generated by Django 5.1.1 on 2024-09-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': [models.OrderBy(models.F('market_value'), descending=True, nulls_last=True), models.OrderBy(models.F('caps'), descending=True, nulls_last=True)]},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['id', 'market_value'], name='players_pla_id_7bc858_idx'),
        ),
    ]
